import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
<<<<<<< HEAD
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
=======
>>>>>>> 8800b54234da290b8f4f91ee0b9921a19c4c9907
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "PressDrive | Car rental made simple",
  description: "Find rental cars and private drivers in one place.",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 8800b54234da290b8f4f91ee0b9921a19c4c9907
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
<<<<<<< HEAD
      <body className="min-h-full flex flex-col bg-[#090a0d] text-white">
        <Navbar />
        {children}
        <Footer />
      </body>
=======
      <body className="min-h-full flex flex-col">{children}</body>
>>>>>>> 8800b54234da290b8f4f91ee0b9921a19c4c9907
    </html>
  );
}
