import { Car } from "@/types/cars";

export const carsDatabase: Record<string, Car> = {
  "1": {
    id: "1",
    make: "Toyota",
    model: "Corolla '23",
    year: "2023",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    rating: "★ 4.2 (38 reviews)",
    price: 40,
    service: "Rental Office",
    style: "economy",
    images: [
      "/cars/corolla/corolla1.jpg",
      "/cars/corolla/corolla2.jpg",
      "/cars/corolla/corolla3.jpg",
    ],
  },

  "2": {
    id: "2",
    make: "Volkswagen",
    model: "Touareg",
    year: "2022",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    rating: "★ 4.8 (24 reviews)",
    price: 15,
    service: "Rental Office",
    style: "suv",
    images: [
      "/cars/suv/suv1.jpg",
      "/cars/suv/suv2.jpg",
      "/cars/suv/suv3.jpg",
    ],
  },

  "3": {
    id: "3",
    make: "Mercedes",
    model: "E-Class",
    year: "2023",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    rating: "★ 4.9 (50 reviews)",
    price: 200,
    service: "Rental Office",
    style: "luxury",
    images: [
      "/cars/e-class/e-class1.jpg",
      "/cars/e-class/e-class2.jpg",
      "/cars/e-class/e-class3.jpg",
    ],
  },

  "4": {
    id: "4",
    make: "Mercedes",
    model: "Classic Sedan",
    year: "2005",
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    rating: "★ 4.5 (15 reviews)",
    price: 10,
    service: "Rental Office",
    style: "economy",
    images: [
      "/cars/sedan/sedan1.jpg",
      "/cars/sedan/sedan2.jpg",
      "/cars/sedan/sedan3.jpg",
    ],
  },

  "5": {
    id: "5",
    make: "Nissan",
    model: "Sunny",
    year: "2022",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    rating: "★ 4.3 (22 reviews)",
    price: 25,
    service: "Rental Office",
    style: "economy",
    images: [
      "/cars/sunny/sunny1.jpg",
      "/cars/sunny/sunny2.jpg",
      "/cars/sunny/sunny3.jpg",
    ],
  },

  "6": {
    id: "6",
    make: "Nissan",
    model: "Rogue",
    year: "2022",
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    rating: "★ 4.4 (30 reviews)",
    price: 40,
    service: "Rental Office",
    style: "suv",
    images: [
      "/cars/rogue/rogue1.jpg",
      "/cars/rogue/rogue2.jpg",
      "/cars/rogue/rogue3.jpg",
    ],
  },

  "7": {
    id: "7",
    make: "Honda",
    model: "Pilot",
    year: "2021",
    seats: 7,
    transmission: "Automatic",
    fuel: "Petrol",
    rating: "★ 4.7 (31 reviews)",
    price: 55,
    service: "Rental Office",
    style: "suv",
    images: [
      "/cars/pilot/pilot1.jpg",
      "/cars/pilot/pilot2.jpg",
      "/cars/pilot/pilot3.jpg",
    ],
  },

  "8": {
    id: "8",
    make: "Hyundai",
    model: "Van (Ahmad Sayed)",
    year: "2020",
    seats: 10,
    transmission: "Automatic",
    fuel: "Diesel",
    rating: "★ 4.6 (18 reviews)",
    price: 20,
    service: "Private Driver",
    style: "suv",
    images: [
      "/cars/hyundai/hyundai1.jpg",
      "/cars/hyundai/hyundai2.jpg",
      "/cars/hyundai/hyundai3.jpg",
    ],
  },

  "9": {
    id: "9",
    make: "BMW",
    model: "Convertible",
    year: "2023",
    seats: 2,
    transmission: "Automatic",
    fuel: "Petrol",
    rating: "★ 4.9 (40 reviews)",
    price: 75,
    service: "Rental Office",
    style: "luxury",
    images: [
      "/cars/bmw/bmw1.jpg",
      "/cars/bmw/bmw2.jpg",
      "/cars/bmw/bmw3.jpg",
    ],
  },
};